### PR TITLE
Nil client script

### PR DESCRIPTION
**Pull request by Inspector-Parrot**
'client/gui.lua' doesnt exist

**Describe Pull request**
The manifest is attempting to import a module that is not present in the current client folder.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

### CODE REVIEW

**Review by Sharkiiie — APPROVED** [review]
LGTM

**Comment by Rtextbook** [comment]
[resources:qb-apartme] Warning: could not find client_script `client/gui.lua` (defined in fxmanifest.lua:19) so i think i have the same issue going on in my server. can i -- it out in the fxmani or is there a resolution?

**Comment by Sharkiiie** [comment]
Just delete the line from the fxmanifest.

**Comment by Inspector-Parrot** [comment]
> [resources:qb-apartme] Warning: could not find client_script `client/gui.lua` (defined in fxmanifest.lua:19) so i think i have the same issue going on in my server. can i -- it out in the fxmani or is there a resolution?

This is a pull request not a issue post. They just need to accept the PR.

**Pull request closed without merging**
